---
- name: installing pkgs in windows server
  hosts: all
  gather_facts: no
  vars:
    pkg_url: https://download-installer.cdn.mozilla.net/pub/firefox/releases/79.0/win64/en-US/Firefox%20Setup%2079.0.msi
    pkg_path: C:\Users\Administrator\Downloads
  tasks:
   - name: downloading package in local directory
     win_get_url:
       url: "{{ pkg_url }}"
       dest: "{{ pkg_path }}"

   - name: installing the package using pacakge module
     win_package:
       path: '{{ pkg_path }}\Firefox Setup 79.0.msi'
       state: present
